bikeshare:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: bikeshare
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '9000') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse') }}"
      secure: false
      verify: false
      threads: 4